### ISSUE TITLE
Adding matches from previous seasons

### ISSUE THREAD

**Issue by r3dunlop** [cpkm/darts-site#81] opened 2019-08-23 01:34 UTC
All matches that are added go to current season. I don't want to add 2017-2018 until this is fixed. "Current" is the only one displayed in amtch view as well. An away match against ICC-2 on Sept 25, 2017 can be used for testing.

**Comment by cpkm** [comment] 2019-08-23 03:15
I'm starting to hunt this down. It seams the season is actually correct, but the query used to populate the season page is yielding odd results. See [here](https://github.com/cpkm/darts-site/blob/b313ffe84a4397117b443bc6ddcbb5ab7fb3e85d/app/main/routes.py#L325)

**Comment by cpkm** [comment] 2019-08-23 03:16
Notice the messed up formatting of the 2018/2019 list of games also.

**Comment by r3dunlop** [comment] 2019-08-23 11:35
I think quite a few of the queries involving the season are misbehaving. The season_from_date function is an issue because it doesn't have any logic if the date is outside of a season. If the season is being set correctly and it's only a query problem, then I can continue entering 2017/2018 whenever I'm sitting watching tv.

**Comment by cpkm** [comment] 2019-08-23 11:37
ya I’m going to fix the match.season and season_from_date. keep entering

**Comment by cpkm** [comment] 2019-08-23 15:46
The bug is fixed in #89 . Continue entering data, it should display normally now.

**Comment by cpkm** [comment] 2019-08-23 16:12
I think this is now basically a duplicate of #74 so I going to close this issue.

**Closed by cpkm** 2019-08-23 16:12 UTC
